version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - ${MONGO_INITDB_ROOT_PORT}
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
